// Code generated by "stringer -type TokenType -trimprefix TOKEN_"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOKEN_TEXT-0]
	_ = x[TOKEN_NL-1]
	_ = x[TOKEN_COMMAND_START-2]
	_ = x[TOKEN_COMMAND_END-3]
	_ = x[TOKEN_COMMAND-4]
	_ = x[TOKEN_COMMAND_ARG-5]
	_ = x[TOKEN_FUNC-6]
	_ = x[TOKEN_START_LOOP-7]
	_ = x[TOKEN_END_LOOP-8]
	_ = x[TOKEN_START_COND-9]
	_ = x[TOKEN_END_COND-10]
	_ = x[TOKEN_EOF-11]
	_ = x[TOKEN_RESET-12]
	_ = x[TOKEN_BOLD-13]
	_ = x[TOKEN_FAINT-14]
	_ = x[TOKEN_ITALIC-15]
	_ = x[TOKEN_UNDERLINE-16]
	_ = x[TOKEN_BLINK_SLOW-17]
	_ = x[TOKEN_BLINK_RAPID-18]
	_ = x[TOKEN_REVERSE-19]
	_ = x[TOKEN_CROSSED_OUT-20]
	_ = x[TOKEN_FG-21]
	_ = x[TOKEN_BG-22]
	_ = x[TOKEN_CURSOR_UP-23]
	_ = x[TOKEN_CURSOR_DOWN-24]
	_ = x[TOKEN_CURSOR_FORWARD-25]
	_ = x[TOKEN_CURSOR_BACKWARD-26]
	_ = x[TOKEN_CURSOR_NEXT_LINE-27]
	_ = x[TOKEN_CURSOR_PREV_LINE-28]
	_ = x[TOKEN_CURSOR_SET_POSITION-29]
	_ = x[TOKEN_SCREEN_CLEAR-30]
	_ = x[TOKEN_LINE_CLEAR-31]
}

const _TokenType_name = "TEXTNLCOMMAND_STARTCOMMAND_ENDCOMMANDCOMMAND_ARGFUNCSTART_LOOPEND_LOOPSTART_CONDEND_CONDEOFRESETBOLDFAINTITALICUNDERLINEBLINK_SLOWBLINK_RAPIDREVERSECROSSED_OUTFGBGCURSOR_UPCURSOR_DOWNCURSOR_FORWARDCURSOR_BACKWARDCURSOR_NEXT_LINECURSOR_PREV_LINECURSOR_SET_POSITIONSCREEN_CLEARLINE_CLEAR"

var _TokenType_index = [...]uint16{0, 4, 6, 19, 30, 37, 48, 52, 62, 70, 80, 88, 91, 96, 100, 105, 111, 120, 130, 141, 148, 159, 161, 163, 172, 183, 197, 212, 228, 244, 263, 275, 285}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
